- name: edit /etc/security/limits.d/90-nproc.conf
  replace:
    path: /etc/security/limits.d/90-nproc.conf
    regexp: " 1024$"
    replace: " 102400"

- name: disable iptables
  service:
    name: iptables
    enabled: no
    state: stopped
