---
- name: add user nginx
  user:
    name: nginx

- name: install dependent packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - automake
    - gcc
    - openssl-devel
    - pcre-devel
    - zlib-devel

- name: copy and unarchive nginx-{{nginx_version}}.tar.gz
  unarchive:
    src: nginx-{{nginx_version}}.tar.gz
    dest: /usr/local/src

- name: configure
  command: ./configure --prefix=/usr/local/nginx --with-http_ssl_module --with-http_stub_status_module
  args:
    chdir: /usr/local/src/nginx-{{nginx_version}}

- name: make
  make:
    chdir: /usr/local/src/nginx-{{nginx_version}}

- name: make install
  make:
    chdir: /usr/local/src/nginx-{{nginx_version}}
    target: install

- name: edit /etc/profile
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: "\n# nginx\nexport PATH=/usr/local/nginx/sbin:$PATH"

- name: link /etc/nginx
  file:
    src: /usr/local/nginx/conf
    dest: /etc/nginx
    state: link

- name: copy /etc/nginx/nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: make directory /etc/nginx/conf.d
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: copy /etc/nginx/conf.d/default_server.conf
  copy:
    src: default_server.conf
    dest: /etc/nginx/conf.d/default_server.conf

- name: copy /etc/nginx/conf.d/www.example.com.conf.demo
  copy:
    src: www.example.com.conf.demo
    dest: /etc/nginx/conf.d/www.example.com.conf.demo

- name: make directory /var/log/nginx
  file:
    path: /var/log/nginx
    state: directory
    owner: nginx
    group: nginx

- include_tasks: patch-centos-6.yml
  when: ansible_distribution_major_version == "6"

- include_tasks: patch-centos-7.yml
  when: ansible_distribution_major_version == "7"
